import type { ProductLot } from '@/types/shop'

/**
 * Datos de ejemplo para desarrollo.
 * En producción vendrán de Supabase, gestionados desde /administrator.
 */
export const productLotsES: ProductLot[] = [
  // === T. PACHANOI ===
  {
    id: 'lot-pac-100-s',
    created_at: '2025-01-15',
    updated_at: '2025-01-15',
    variety_slug: 'trichocereus-pachanoi',
    name: 'Lote 100 uds · T. Pachanoi · 10-15 cm',
    sku: 'LOT-PAC-100-S',
    description: 'Lote de 100 unidades de Trichocereus Pachanoi (San Pedro) de 10 a 15 cm de altura. Plantas jóvenes y vigorosas, enraizadas en maceta. Ideales para reventa en garden center o crecimiento en vivero.',
    variety_name: 'T. Pachanoi',
    size_range: '10-15 cm',
    units_per_lot: 100,
    price: 350,
    currency: 'EUR',
    lots_available: 12,
    status: 'active',
    image_url: '/images/products/producto_trichocereus_pachanoi_1.png',
    gallery: [],
    highlights: [
      'Pasaporte fitosanitario UE incluido',
      'Plantas enraizadas y aclimatadas',
      'Embalaje individual con protección',
      'Envío en 48-72h (España peninsular)',
    ],
    weight_kg: 25,
    shipping_notes: 'Envío en caja reforzada. Protección individual por planta.',
    meta_title: 'Lote 100 T. Pachanoi 10-15cm | Tricholand',
    meta_description: 'Compra al por mayor T. Pachanoi 10-15cm. Lote de 100 unidades con pasaporte fitosanitario UE.',
    sort_order: 1,
  },
  {
    id: 'lot-pac-100-m',
    created_at: '2025-01-15',
    updated_at: '2025-01-15',
    variety_slug: 'trichocereus-pachanoi',
    name: 'Lote 100 uds · T. Pachanoi · 20-30 cm',
    sku: 'LOT-PAC-100-M',
    description: 'Lote de 100 unidades de Trichocereus Pachanoi de 20-30 cm. Tamaño medio ideal para venta directa.',
    variety_name: 'T. Pachanoi',
    size_range: '20-30 cm',
    units_per_lot: 100,
    price: 650,
    currency: 'EUR',
    lots_available: 8,
    status: 'active',
    image_url: '/images/products/producto_trichocereus_pachanoi_1.png',
    gallery: [],
    highlights: ['Tamaño ideal para venta directa', 'Ejemplares seleccionados', 'Pasaporte fito UE incluido', 'Disponible todo el año'],
    weight_kg: 45,
    shipping_notes: 'Envío en palé para 3+ lotes.',
    meta_title: 'Lote 100 T. Pachanoi 20-30cm | Tricholand',
    meta_description: 'Lote mayorista T. Pachanoi 20-30cm. 100 unidades para reventa profesional.',
    sort_order: 2,
  },
  {
    id: 'lot-pac-50-l',
    created_at: '2025-01-15',
    updated_at: '2025-01-15',
    variety_slug: 'trichocereus-pachanoi',
    name: 'Lote 50 uds · T. Pachanoi · 40-50 cm',
    sku: 'LOT-PAC-50-L',
    description: 'Lote de 50 unidades de gran tamaño (40-50 cm). Ejemplares maduros para paisajismo o venta premium.',
    variety_name: 'T. Pachanoi',
    size_range: '40-50 cm',
    units_per_lot: 50,
    price: 750,
    currency: 'EUR',
    lots_available: 3,
    status: 'active',
    image_url: '/images/products/producto_trichocereus_pachanoi_1.png',
    gallery: [],
    highlights: ['Ejemplares premium de gran tamaño', 'Ideal para paisajismo', 'Stock limitado', 'Pasaporte fito UE incluido'],
    weight_kg: 60,
    shipping_notes: 'Envío en palé obligatorio.',
    meta_title: 'Lote 50 T. Pachanoi 40-50cm Premium | Tricholand',
    meta_description: 'Lote premium T. Pachanoi 40-50cm. 50 ejemplares de gran tamaño.',
    sort_order: 3,
  },
  // === T. PERUVIANUS ===
  {
    id: 'lot-per-100-s',
    created_at: '2025-01-15',
    updated_at: '2025-01-15',
    variety_slug: 'trichocereus-peruvianus',
    name: 'Lote 100 uds · T. Peruvianus · 10-15 cm',
    sku: 'LOT-PER-100-S',
    description: 'Lote de 100 unidades de Trichocereus Peruvianus de 10-15 cm. Variedad muy apreciada por coleccionistas.',
    variety_name: 'T. Peruvianus',
    size_range: '10-15 cm',
    units_per_lot: 100,
    price: 450,
    currency: 'EUR',
    lots_available: 6,
    status: 'active',
    image_url: '/images/products/producto_trichocereus_peruvianus_1.png',
    gallery: [],
    highlights: ['Espinación decorativa prominente', 'Gran variabilidad entre clones', 'Pasaporte fito UE incluido', 'Muy demandado por coleccionistas'],
    weight_kg: 28,
    shipping_notes: 'Embalaje especial para proteger espinas.',
    meta_title: 'Lote 100 T. Peruvianus 10-15cm | Tricholand',
    meta_description: 'Lote mayorista T. Peruvianus 10-15cm. 100 unidades con pasaporte fito UE.',
    sort_order: 4,
  },
  {
    id: 'lot-per-100-m',
    created_at: '2025-01-15',
    updated_at: '2025-01-15',
    variety_slug: 'trichocereus-peruvianus',
    name: 'Lote 100 uds · T. Peruvianus · 20-30 cm',
    sku: 'LOT-PER-100-M',
    description: 'Lote de 100 unidades de Trichocereus Peruvianus de 20-30 cm. Tamaño medio para venta directa.',
    variety_name: 'T. Peruvianus',
    size_range: '20-30 cm',
    units_per_lot: 100,
    price: 750,
    currency: 'EUR',
    lots_available: 4,
    status: 'active',
    image_url: '/images/products/producto_trichocereus_peruvianus_1.png',
    gallery: [],
    highlights: ['Tamaño perfecto para venta directa', 'Espinas bien desarrolladas', 'Pasaporte fito UE incluido', 'Selección de clones variados'],
    weight_kg: 48,
    shipping_notes: 'Envío en palé para 2+ lotes.',
    meta_title: 'Lote 100 T. Peruvianus 20-30cm | Tricholand',
    meta_description: 'Lote mayorista T. Peruvianus 20-30cm. 100 unidades seleccionadas.',
    sort_order: 5,
  },
  // === T. BRIDGESII ===
  {
    id: 'lot-bri-100-s',
    created_at: '2025-01-15',
    updated_at: '2025-01-15',
    variety_slug: 'trichocereus-bridgesii',
    name: 'Lote 100 uds · T. Bridgesii · 10-15 cm',
    sku: 'LOT-BRI-100-S',
    description: 'Lote de 100 unidades de Trichocereus Bridgesii de 10-15 cm. Producción limitada.',
    variety_name: 'T. Bridgesii',
    size_range: '10-15 cm',
    units_per_lot: 100,
    price: 550,
    currency: 'EUR',
    lots_available: 2,
    status: 'active',
    image_url: '/images/products/producto_trichocereus_bridgessi_1.png',
    gallery: [],
    highlights: ['Stock limitado — alta demanda', 'Morfología única', 'Pasaporte fito UE incluido', 'Reserva anticipada recomendada'],
    weight_kg: 26,
    shipping_notes: 'Stock limitado. Reserva anticipada recomendada.',
    meta_title: 'Lote 100 T. Bridgesii 10-15cm | Tricholand',
    meta_description: 'Lote mayorista T. Bridgesii 10-15cm. Producción limitada.',
    sort_order: 6,
  },
  // === T. TERSCHECKII ===
  {
    id: 'lot-ter-50-m',
    created_at: '2025-01-15',
    updated_at: '2025-01-15',
    variety_slug: 'trichocereus-pasacana-terscheckii',
    name: 'Lote 50 uds · T. Terscheckii · 30-50 cm',
    sku: 'LOT-TER-50-M',
    description: 'Lote de 50 unidades de Trichocereus Terscheckii de 30-50 cm. El gigante del género.',
    variety_name: 'T. Terscheckii',
    size_range: '30-50 cm',
    units_per_lot: 50,
    price: 600,
    currency: 'EUR',
    lots_available: 5,
    status: 'active',
    image_url: '/images/varieties/Trichocereus_terscheckii_1.png',
    gallery: [],
    highlights: ['El cactus más grande del género', 'Resistencia extrema al frío (-8°C)', 'Porte arquitectónico', 'Pasaporte fito UE incluido'],
    weight_kg: 55,
    shipping_notes: 'Envío en palé. Embalaje reforzado.',
    meta_title: 'Lote 50 T. Terscheckii 30-50cm | Tricholand',
    meta_description: 'Lote mayorista T. Terscheckii 30-50cm. 50 ejemplares para paisajismo.',
    sort_order: 7,
  },
  // === T. SPACHIANUS PORTAINJERTO ===
  {
    id: 'lot-spa-200-s',
    created_at: '2025-01-15',
    updated_at: '2025-01-15',
    variety_slug: 'trichocereus-spachianus',
    name: 'Lote 200 uds · T. Spachianus · 10-15 cm (portainjerto)',
    sku: 'LOT-SPA-200-PI',
    description: 'Lote de 200 unidades seleccionadas como portainjerto profesional. Máximo volumen, mínimo precio unitario.',
    variety_name: 'T. Spachianus',
    size_range: '10-15 cm',
    units_per_lot: 200,
    price: 500,
    currency: 'EUR',
    lots_available: 4,
    status: 'active',
    image_url: '/images/vivero/vivero-020.jpg',
    gallery: [],
    highlights: ['Portainjerto profesional', '200 uds/lote — máximo volumen', 'Calibre homogéneo', 'Precio unitario más bajo'],
    weight_kg: 35,
    shipping_notes: 'Ideal para pedidos recurrentes.',
    meta_title: 'Lote 200 T. Spachianus Portainjerto | Tricholand',
    meta_description: 'Lote de 200 T. Spachianus portainjerto. El más demandado por viveros profesionales.',
    sort_order: 8,
  },
  // === MIX ===
  {
    id: 'lot-mix-100-s',
    created_at: '2025-01-15',
    updated_at: '2025-01-15',
    variety_slug: 'otros-cactus',
    name: 'Lote Mix 100 uds · Variedades surtidas · 10-20 cm',
    sku: 'LOT-MIX-100',
    description: 'Lote de 100 unidades de variedades surtidas. Selección variada ideal para diversificar tu oferta.',
    variety_name: 'Mix Trichocereus',
    size_range: '10-20 cm',
    units_per_lot: 100,
    price: 400,
    currency: 'EUR',
    lots_available: 6,
    status: 'active',
    image_url: '/images/varieties/Otros_cactus.png',
    gallery: [],
    highlights: ['Mínimo 4 variedades por lote', 'Ideal para diversificar oferta', 'Selección del equipo', 'Mejor relación calidad-precio'],
    weight_kg: 30,
    shipping_notes: 'Composición puede variar según disponibilidad.',
    meta_title: 'Lote Mix 100 Trichocereus Surtido | Tricholand',
    meta_description: 'Lote surtido de 100 Trichocereus. La forma más económica de diversificar.',
    sort_order: 9,
  },
]

export function getProductLotById(id: string): ProductLot | undefined {
  return productLotsES.find((p) => p.id === id)
}

export function getActiveProductLots(): ProductLot[] {
  return productLotsES.filter((p) => p.status === 'active').sort((a, b) => a.sort_order - b.sort_order)
}

export function getProductLotsByVariety(varietySlug: string): ProductLot[] {
  return productLotsES.filter((p) => p.variety_slug === varietySlug && p.status === 'active').sort((a, b) => a.sort_order - b.sort_order)
}
