import type { Variety } from '@/types/variety'

export const varietiesES: Variety[] = [
  {
    slug: 'trichocereus-pachanoi',
    code: 'TRI-PAC',
    name: 'Trichocereus Pachanoi',
    scientificName: 'Echinopsis pachanoi',
    commonName: 'San Pedro',
    description: 'El Trichocereus pachanoi, comúnmente conocido como San Pedro, es una de las cactáceas columnares más emblemáticas y cultivadas del mundo. Originario de los Andes de Ecuador y Perú, donde crece entre los 2.000 y 3.000 metros de altitud, este cactus se caracteriza por su crecimiento vigoroso, sus costillas bien definidas (generalmente entre 6 y 8) y sus espinas cortas o, en muchas variedades, prácticamente ausentes. Su color verde azulado y su porte elegante lo convierten en una pieza ornamental de primer nivel para jardines, terrazas y proyectos de paisajismo. En condiciones óptimas puede alcanzar alturas superiores a los 6 metros, y produce flores blancas nocturnas de gran tamaño y belleza. Es una de las especies más demandadas por viveros y garden centers europeos tanto por su valor ornamental como por su facilidad de cultivo y adaptación al clima mediterráneo.',
    image: '/images/varieties/Trichocereus_Pachanoi_1.png',
    imageAlt: 'Trichocereus Pachanoi - San Pedro cactus',
    gallery: [
      '/images/varieties/Trichocereus_Pachanoi_2.png',
      '/images/products/producto_trichocereus_pachanoi_1.png',
      '/images/products/producto_trichocereus_pachanoi_bio_1.png',
    ],
    sizeRange: '10–50 cm',
    stock: 'available',
    highlights: [
      'Crecimiento rápido: hasta 30 cm/año en condiciones óptimas',
      'Adaptación excelente al clima mediterráneo',
      'Floración nocturna espectacular (flores blancas de hasta 22 cm)',
      'Ideal como portainjerto por su vigor',
      'Mínimo mantenimiento una vez establecido',
      'Alta resistencia a plagas comunes',
    ],
    care: {
      light: 'Pleno sol a semisombra. Mínimo 6 horas de luz directa al día para un crecimiento óptimo.',
      water: 'Riego moderado en primavera-verano (cada 7-10 días). Reducir drásticamente en invierno. Evitar encharcamiento.',
      temperature: 'Tolera hasta -2°C de forma puntual si el sustrato está seco. Rango óptimo: 15-35°C.',
      soil: 'Sustrato muy drenante: mezcla de tierra vegetal, perlita y arena gruesa (proporción 40-30-30).',
    },
  },
  {
    slug: 'trichocereus-peruvianus',
    code: 'TRI-PER',
    name: 'Trichocereus Peruvianus',
    scientificName: 'Echinopsis peruviana',
    commonName: 'Antorcha Peruana',
    description: 'El Trichocereus peruvianus, conocido como Antorcha Peruana, es un cactus columnar robusto originario de las vertientes occidentales de los Andes peruanos. Se distingue del pachanoi por sus espinas más largas y prominentes, sus costillas más profundas (típicamente 6-8, aunque algunos clones presentan hasta 10) y su tonalidad verde-grisácea con matices azulados. Es una especie de crecimiento vigoroso que puede superar los 4 metros de altura en su hábitat natural. Produce flores blancas grandes y muy perfumadas que se abren por la noche. El peruvianus es especialmente valorado en colecciones y viveros europeos por la gran variabilidad morfológica entre sus clones, ofreciendo una amplia gama de formas, colores y patrones de espinación que lo convierten en una pieza de coleccionismo muy apreciada.',
    image: '/images/varieties/Trichocereus_peruvianus_1.png',
    imageAlt: 'Trichocereus Peruvianus - Antorcha Peruana',
    gallery: [
      '/images/products/producto_trichocereus_peruvianus_1.png',
    ],
    sizeRange: '10–40 cm',
    stock: 'available',
    highlights: [
      'Gran variabilidad morfológica entre clones',
      'Espinación decorativa y prominente',
      'Excelente resistencia al frío (hasta -4°C seco)',
      'Flores blancas nocturnas muy perfumadas',
      'Pieza de coleccionismo muy demandada',
      'Crecimiento columnar robusto y elegante',
    ],
    care: {
      light: 'Pleno sol. Tolera algo de sombra pero pierde vigor y color.',
      water: 'Riego moderado en período de crecimiento. Muy resistente a la sequía.',
      temperature: 'Más resistente al frío que el pachanoi. Soporta hasta -4°C con sustrato seco.',
      soil: 'Sustrato mineral muy drenante. Mayor proporción de arena y grava que para pachanoi.',
    },
  },
  {
    slug: 'trichocereus-bridgesii',
    code: 'TRI-BRI',
    name: 'Trichocereus Bridgesii',
    scientificName: 'Echinopsis lageniformis',
    commonName: 'Achuma / Wachuma',
    description: 'El Trichocereus bridgesii, conocido como Achuma o Wachuma en su Bolivia natal, es un cactus columnar de crecimiento rápido que se distingue por sus costillas profundas y bien definidas (generalmente 4-8), sus espinas largas y su característica tonalidad verde oscura. Es una de las especies de Trichocereus más fáciles de identificar gracias a su morfología única, con secciones que se estrechan y ensanchan de forma característica. Originario de las tierras altas de Bolivia, entre los 2.500 y 3.500 metros de altitud, se ha adaptado perfectamente al cultivo en climas mediterráneos europeos. Su producción es más limitada que la del pachanoi, lo que lo convierte en una pieza especialmente buscada por coleccionistas y viveros especializados.',
    image: '/images/varieties/Trichocereus_Bridgessi_1.png',
    imageAlt: 'Trichocereus Bridgesii - Achuma cactus',
    gallery: [
      '/images/varieties/Trichocereus_Bridgessi_2.png',
      '/images/products/producto_trichocereus_bridgessi_1.png',
    ],
    sizeRange: '10–30 cm',
    stock: 'limited',
    highlights: [
      'Morfología única y fácilmente reconocible',
      'Crecimiento rápido en condiciones adecuadas',
      'Pieza de coleccionismo muy buscada',
      'Adaptado al cultivo mediterráneo europeo',
      'Flores blancas grandes y aromáticas',
      'Producción limitada — alta demanda',
    ],
    care: {
      light: 'Pleno sol. Requiere buena exposición para mantener forma compacta.',
      water: 'Riego regular en verano, reducir en otoño, suspender en invierno.',
      temperature: 'Tolera hasta -2°C brevemente. Proteger de heladas prolongadas.',
      soil: 'Sustrato muy drenante con buena proporción de material mineral.',
    },
  },
  {
    slug: 'trichocereus-pasacana-terscheckii',
    code: 'TRI-TER',
    name: 'Trichocereus Terscheckii',
    scientificName: 'Echinopsis terscheckii',
    commonName: 'Cardón Grande',
    description: 'El Trichocereus terscheckii, conocido como Cardón Grande o Cardón de la Puna, es el gigante del género. Originario del noroeste argentino, donde forma bosques de cactus impresionantes en las provincias de Salta, Jujuy, Tucumán y Catamarca, puede alcanzar alturas de hasta 10-12 metros en su hábitat natural, convirtiéndose en el cactus más alto de Argentina. Se caracteriza por su tronco grueso y leñoso, sus múltiples brazos (en ejemplares maduros), sus numerosas costillas (14-17) y sus espinas robustas de color amarillo a marrón. Es una especie de crecimiento lento comparado con otras del género, pero de una longevidad excepcional, pudiendo vivir varios siglos. En Europa se cultiva como ejemplar ornamental de gran porte, ideal para jardines de estilo desértico y proyectos de paisajismo que requieran elementos arquitectónicos vegetales de impacto.',
    image: '/images/varieties/Trichocereus_terscheckii_1.png',
    imageAlt: 'Trichocereus Terscheckii - Cardón Grande',
    gallery: [
      '/images/varieties/Trichocereus_terscheckii_2.png',
      '/images/varieties/Trichocereus_pasacana_1.png',
    ],
    sizeRange: '20–100 cm',
    stock: 'available',
    highlights: [
      'El cactus más grande del género: hasta 12 m en hábitat',
      'Porte arquitectónico impresionante',
      'Longevidad excepcional (varios siglos)',
      'Resistencia extrema al frío (hasta -8°C)',
      'Ideal para jardines de gran impacto visual',
      'Disponible en tamaños grandes (hasta 100 cm)',
    ],
    care: {
      light: 'Pleno sol obligatorio. Requiere máxima exposición.',
      water: 'Muy resistente a la sequía. Riego esporádico en verano.',
      temperature: 'El más resistente al frío del género. Soporta hasta -8°C con sustrato seco.',
      soil: 'Sustrato muy mineral y pobre. Arena gruesa, grava y poca materia orgánica.',
    },
  },
  {
    slug: 'trichocereus-macrogonus',
    code: 'TRI-MAC',
    name: 'Trichocereus Macrogonus',
    scientificName: 'Echinopsis macrogona',
    commonName: 'San Pedro Azul',
    description: 'El Trichocereus macrogonus, frecuentemente llamado San Pedro Azul por su distintiva tonalidad verde-azulada, es un cactus columnar originario de Bolivia y Perú. Se caracteriza por sus costillas pronunciadas y angulosas (generalmente 6-7), sus espinas cortas y su epidermis cerosa que le confiere ese brillo azulado tan apreciado. Es una especie de crecimiento moderado a rápido que puede alcanzar los 4-5 metros de altura. En el mercado viverístico europeo es muy apreciado por su color único, que aporta un contraste visual interesante cuando se combina con otras variedades de Trichocereus de tonos más verdes. Produce flores blancas de gran tamaño.',
    image: '/images/vivero/vivero-010.jpg',
    imageAlt: 'Trichocereus Macrogonus - San Pedro Azul',
    gallery: [
      '/images/vivero/vivero-011.jpg',
    ],
    sizeRange: '15–35 cm',
    stock: 'available',
    highlights: [
      'Color verde-azulado único y muy decorativo',
      'Epidermis cerosa con brillo característico',
      'Excelente para combinar con otras variedades',
      'Crecimiento moderado a rápido',
      'Costillas pronunciadas y angulosas muy estéticas',
      'Buena adaptación al clima europeo',
    ],
    care: {
      light: 'Pleno sol a semisombra ligera. El color azulado se acentúa con buena luz.',
      water: 'Riego moderado. Similar al pachanoi en frecuencia.',
      temperature: 'Tolera hasta -2°C con sustrato seco. Proteger de heladas prolongadas.',
      soil: 'Sustrato drenante estándar para cactus columnares.',
    },
  },
  {
    slug: 'trichocereus-spachianus',
    code: 'TRI-SPA',
    name: 'Trichocereus Spachianus',
    scientificName: 'Echinopsis spachiana',
    commonName: 'Antorcha Dorada',
    description: 'El Trichocereus spachianus, conocido como Antorcha Dorada, es un cactus columnar originario del norte de Argentina. Se distingue por sus espinas doradas que contrastan con su epidermis verde brillante, creando un efecto visual muy atractivo. Presenta costillas numerosas (10-15) y bien definidas, y una forma columnar limpia y recta. Es una de las especies más utilizadas como portainjerto profesional por su gran vigor y compatibilidad con otros cactus, lo que lo convierte en un producto estratégico para viveros que realizan injertos. Además de su uso como portainjerto, es valorado como planta ornamental por su porte elegante y sus espinas doradas. Produce flores blancas de tamaño mediano.',
    image: '/images/vivero/vivero-020.jpg',
    imageAlt: 'Trichocereus Spachianus - Antorcha Dorada',
    gallery: [
      '/images/vivero/vivero-021.jpg',
    ],
    sizeRange: '10–30 cm',
    stock: 'limited',
    highlights: [
      'Espinas doradas muy decorativas',
      'Portainjerto profesional de referencia',
      'Gran compatibilidad para injertos con otros cactus',
      'Crecimiento vigoroso y forma columnar limpia',
      'Producto estratégico para viveros profesionales',
      'Producción limitada — stock bajo demanda',
    ],
    care: {
      light: 'Pleno sol. Las espinas doradas brillan más con exposición directa.',
      water: 'Riego moderado en temporada de crecimiento. Resistente a la sequía.',
      temperature: 'Buena resistencia al frío: hasta -5°C con sustrato seco.',
      soil: 'Sustrato drenante estándar. Tolera suelos algo más ricos que otras especies.',
    },
  },
  {
    slug: 'otros-cactus',
    code: 'TRI-COL',
    name: 'Otros cactus',
    scientificName: 'Varias especies',
    commonName: 'Colección',
    description: 'Además de nuestras variedades principales de Trichocereus, cultivamos una selección de cactáceas columnares y globulares de interés para viveros y coleccionistas. Nuestra colección incluye híbridos selectos de Trichocereus, variedades raras y formas crestadas o monstruosas que son piezas únicas de alto valor para coleccionistas. Consulte disponibilidad y variedades concretas contactando con nuestro equipo comercial.',
    image: '/images/varieties/Otros_cactus.png',
    imageAlt: 'Colección de cactus Tricholand',
    gallery: [
      '/images/varieties/Otros_cactus_2.png',
      '/images/products/producto_otros_pachanoi_crestado_1.png',
    ],
    sizeRange: 'Variable',
    stock: 'available',
    highlights: [
      'Híbridos selectos de Trichocereus',
      'Formas crestadas y monstruosas',
      'Piezas únicas de coleccionismo',
      'Variedades raras bajo pedido',
      'Cactus globulares selectos',
      'Consultar disponibilidad',
    ],
    care: {
      light: 'Variable según especie. Consultar ficha individual.',
      water: 'Variable según especie.',
      temperature: 'Variable según especie.',
      soil: 'Sustrato drenante como base. Ajustar según especie.',
    },
  },
]

export function getVarietyBySlug(slug: string): Variety | undefined {
  return varietiesES.find((v) => v.slug === slug)
}

export function getAllVarietySlugs(): string[] {
  return varietiesES.map((v) => v.slug)
}
